#!/usr/bin/env bash
# Displays information about subdomains.
sub_domains () {
    info=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 |
    tr '\n' ' ')echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 "
    record and points to " $3}'
}
if [ "$#" == 1 ]
then
  sub_domains "$1" "www"
  sub_domains "$1" "lb-01"
  sub_domains "$1" "web-01"
  sub_domains "$1" "web-02"
elif [ "$#" == 2 ]
then
  sub_domains "$1" "$2"
fi

