#!/usr/bin/env bash
# Installs HAProxy and configures it to send traffic to web-01 and web-02.

sudo apt-get -y update
sudo apt-get -y install haproxy
echo "
frontend mutais_frontend
    bind *:80
    mode http
    default_backend mutais_backend
backend mutais_backend
    balance roundrobin
    server 166243-web-01 52.3.243.47:80 check
    server 166243-web-02 52.86.147.16:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
